//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Format {
    #[serde(rename = "markdown")]
    Markdown,
    #[serde(rename = "plain")]
    Plain,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BodySection {
    pub format: Option<Format>,
    pub text: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Content {
    pub body: Option<BodySection>,
    pub headline: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Highlight {
    pub text: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Metadata {
    pub author: String,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Document {
    pub content: Option<Content>,
    pub count: Option<i64>,
    #[serde(rename = "foo-bar")]
    pub foo_bar: Option<String>,
    pub highlights: Option<Vec<Highlight>>,
    pub metadata: Metadata,
    pub published: Option<bool>,
    pub score: Option<f64>,
    pub tags: Option<Vec<String>>,
    pub version: String,
    pub weights: Option<Vec<f64>>,
}

