//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

/// Text format.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum Format {
    #[serde(rename = "markdown")]
    Markdown,
    #[serde(rename = "plain")]
    Plain,
}

fn default_BodySection_format() -> Option<Format> {
    Some(Format::Plain)
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BodySection {
    /// Text format.
    #[serde(default = "default_BodySection_format")]
    pub format: Option<Format>,
    pub text: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Content {
    pub body: Option<BodySection>,
    pub headline: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Highlight {
    pub text: Option<String>,
}

/// Author and timestamp.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Metadata {
    pub author: String,
    pub created_at: Option<String>,
}

/// Root document with version and metadata.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Document {
    pub content: Option<Content>,
    #[serde(default)]
    pub count: Option<i64>,
    #[serde(rename = "foo-bar")]
    pub foo_bar: Option<String>,
    pub highlights: Option<Vec<Highlight>>,
    /// Author and timestamp.
    pub metadata: Metadata,
    pub published: Option<bool>,
    pub score: Option<f64>,
    pub tags: Option<Vec<String>>,
    /// Schema version string.
    pub version: String,
    pub weights: Option<Vec<f64>>,
}

