//! Integration test: public API for schema parsing and code generation, and CLI binary.

use json_schema_rs::{JsonSchema, generate_rust};
use std::io::Write;
use std::process::Command;
use std::process::Stdio;

fn jsonschemars_bin() -> std::path::PathBuf {
    if let Ok(path) = std::env::var("CARGO_BIN_EXE_jsonschemars") {
        return std::path::PathBuf::from(path);
    }
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo");
    let target_dir = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| {
        std::path::PathBuf::from(&manifest_dir)
            .join("..")
            .join("target")
            .into_os_string()
            .into_string()
            .unwrap()
    });
    let bin = std::path::Path::new(&target_dir)
        .join("debug")
        .join("jsonschemars");
    assert!(
        bin.exists(),
        "jsonschemars binary not found at {}",
        bin.display()
    );
    bin
}

#[test]
fn cli_generate_rust_single_file_to_output_dir() {
    let schema_json =
        r#"{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}"#;
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let schema_path = temp_dir.path().join("schema.json");
    std::fs::write(&schema_path, schema_json).expect("write schema");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            schema_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "exit success: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let out_path = out_dir.path().join("schema.rs");
    let actual = std::fs::read_to_string(&out_path).expect("read output");
    let expected = r"//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Root {
    pub id: String,
}

";
    assert_eq!(expected, actual);
}

#[test]
fn cli_generate_unsupported_language_exit_nonzero_and_stderr() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let schema_path = temp_dir.path().join("x.json");
    std::fs::write(
        &schema_path,
        r#"{"type":"object","properties":{"x":{"type":"string"}}}"#,
    )
    .expect("write schema");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "python",
            "-o",
            out_dir.path().to_str().unwrap(),
            schema_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(!output.status.success(), "generate python should fail");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert!(
        stderr.contains("unsupported"),
        "stderr should mention unsupported language: {stderr}"
    );
}

#[test]
fn cli_generate_rust_multiple_files_mirror_paths() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let a_path = temp_dir.path().join("a.json");
    let b_path = temp_dir.path().join("b.json");
    std::fs::write(
        &a_path,
        r#"{"type":"object","properties":{"a":{"type":"string"}}}"#,
    )
    .expect("write a");
    std::fs::write(
        &b_path,
        r#"{"type":"object","properties":{"b":{"type":"string"}}}"#,
    )
    .expect("write b");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            a_path.to_str().unwrap(),
            b_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let a_rs = std::fs::read_to_string(out_dir.path().join("a.rs")).expect("read a.rs");
    let b_rs = std::fs::read_to_string(out_dir.path().join("b.rs")).expect("read b.rs");
    assert!(
        a_rs.contains("pub a: Option<String>"),
        "a.rs should have field a"
    );
    assert!(
        b_rs.contains("pub b: Option<String>"),
        "b.rs should have field b"
    );
}

#[test]
fn cli_generate_rust_dir_recursive_mirrors_structure() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let nested = temp_dir.path().join("nested");
    std::fs::create_dir_all(&nested).expect("create nested");
    std::fs::write(
        temp_dir.path().join("root.json"),
        r#"{"type":"object","properties":{"x":{"type":"string"}}}"#,
    )
    .expect("write root");
    std::fs::write(
        nested.join("child.json"),
        r#"{"type":"object","properties":{"y":{"type":"string"}}}"#,
    )
    .expect("write child");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            temp_dir.path().to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let root_rs = std::fs::read_to_string(out_dir.path().join("root.rs")).expect("read root.rs");
    let child_rs = std::fs::read_to_string(out_dir.path().join("nested").join("child.rs"))
        .expect("read nested/child.rs");
    assert!(
        root_rs.contains("pub x: Option<String>"),
        "root.rs should have field x"
    );
    assert!(
        child_rs.contains("pub y: Option<String>"),
        "nested/child.rs should have field y"
    );
}

#[test]
fn cli_validate_valid_payload_exit_zero() {
    let schema_json = r#"{"type":"object","properties":{"x":{"type":"string"}}}"#;
    let mut schema_file = tempfile::NamedTempFile::new().expect("temp schema");
    std::io::Write::write_all(&mut schema_file, schema_json.as_bytes()).expect("write schema");
    schema_file.flush().expect("flush schema");
    let payload_json = r#"{"x":"ok"}"#;
    let mut child = Command::new(jsonschemars_bin())
        .args(["validate", "-s", schema_file.path().to_str().unwrap()])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn jsonschemars");
    std::io::Write::write_all(child.stdin.as_mut().unwrap(), payload_json.as_bytes())
        .expect("write payload");
    let output = child.wait_with_output().expect("wait jsonschemars");
    assert!(
        output.status.success(),
        "validate should succeed: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn cli_validate_invalid_payload_exit_nonzero_and_stderr() {
    let schema_json = r#"{"type":"object","required":["id"]}"#;
    let payload_json = r"{}";
    let mut schema_file = tempfile::NamedTempFile::new().expect("temp schema");
    std::io::Write::write_all(&mut schema_file, schema_json.as_bytes()).expect("write schema");
    schema_file.flush().expect("flush schema");
    let mut child = Command::new(jsonschemars_bin())
        .args(["validate", "-s", schema_file.path().to_str().unwrap()])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn jsonschemars");
    std::io::Write::write_all(child.stdin.as_mut().unwrap(), payload_json.as_bytes())
        .expect("write payload");
    let output = child.wait_with_output().expect("wait jsonschemars");
    assert!(!output.status.success(), "validate should fail");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert!(
        stderr.contains("missing required"),
        "stderr should mention missing required: {stderr}"
    );
}

#[test]
fn integration_parse_and_generate() {
    let json = r#"{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}"#;
    let schema: JsonSchema = serde_json::from_str(json).expect("parse schema");
    let bytes = generate_rust(&[schema]).expect("generate");
    let actual = String::from_utf8(bytes[0].clone()).expect("utf8");
    let expected = r"//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Root {
    pub id: String,
}

";
    assert_eq!(expected, actual);
}
