//! Integration test: public API for schema parsing and code generation.

use json_schema_rs::{Schema, generate_rust};
use std::io::Cursor;

#[test]
fn integration_parse_and_generate() {
    let json = r#"{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}"#;
    let schema: Schema = serde_json::from_str(json).expect("parse schema");
    let mut out = Cursor::new(Vec::new());
    generate_rust(&schema, &mut out).expect("generate");
    let actual = String::from_utf8(out.into_inner()).expect("utf8");
    let expected = r"//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Root {
    pub id: String,
}

";
    assert_eq!(expected, actual);
}
