//! Integration test: public API for schema parsing and code generation, and CLI binary.

use json_schema_rs::{
    CodeGenSettings, JsonSchema, JsonSchemaSettings, generate_rust, parse_schema,
};
use std::io::Write;
use std::process::Command;
use std::process::Stdio;

fn jsonschemars_bin() -> std::path::PathBuf {
    if let Ok(path) = std::env::var("CARGO_BIN_EXE_jsonschemars") {
        return std::path::PathBuf::from(path);
    }
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by Cargo");
    let target_dir = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| {
        std::path::PathBuf::from(&manifest_dir)
            .join("..")
            .join("target")
            .into_os_string()
            .into_string()
            .unwrap()
    });
    let bin = std::path::Path::new(&target_dir)
        .join("debug")
        .join("jsonschemars");
    assert!(
        bin.exists(),
        "jsonschemars binary not found at {}",
        bin.display()
    );
    bin
}

#[test]
fn cli_generate_rust_single_file_to_output_dir() {
    let schema_json =
        r#"{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}"#;
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let schema_path = temp_dir.path().join("schema.json");
    std::fs::write(&schema_path, schema_json).expect("write schema");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            schema_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "exit success: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let out_path = out_dir.path().join("schema.rs");
    let actual = std::fs::read_to_string(&out_path).expect("read output");
    let expected = r"//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Root {
    pub id: String,
}

";
    assert_eq!(expected, actual);
}

#[test]
fn cli_generate_unsupported_language_exit_nonzero_and_stderr() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let schema_path = temp_dir.path().join("x.json");
    std::fs::write(
        &schema_path,
        r#"{"type":"object","properties":{"x":{"type":"string"}}}"#,
    )
    .expect("write schema");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "python",
            "-o",
            out_dir.path().to_str().unwrap(),
            schema_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(!output.status.success(), "generate python should fail");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert!(
        stderr.contains("unsupported"),
        "stderr should mention unsupported language: {stderr}"
    );
}

#[test]
fn cli_generate_rust_multiple_files_mirror_paths() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let a_path = temp_dir.path().join("a.json");
    let b_path = temp_dir.path().join("b.json");
    std::fs::write(
        &a_path,
        r#"{"type":"object","properties":{"a":{"type":"string"}}}"#,
    )
    .expect("write a");
    std::fs::write(
        &b_path,
        r#"{"type":"object","properties":{"b":{"type":"string"}}}"#,
    )
    .expect("write b");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            a_path.to_str().unwrap(),
            b_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let a_rs = std::fs::read_to_string(out_dir.path().join("a.rs")).expect("read a.rs");
    let b_rs = std::fs::read_to_string(out_dir.path().join("b.rs")).expect("read b.rs");
    assert!(
        a_rs.contains("pub a: Option<String>"),
        "a.rs should have field a"
    );
    assert!(
        b_rs.contains("pub b: Option<String>"),
        "b.rs should have field b"
    );
}

#[test]
fn cli_generate_rust_dir_recursive_mirrors_structure() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let nested = temp_dir.path().join("nested");
    std::fs::create_dir_all(&nested).expect("create nested");
    std::fs::write(
        temp_dir.path().join("root.json"),
        r#"{"type":"object","properties":{"x":{"type":"string"}}}"#,
    )
    .expect("write root");
    std::fs::write(
        nested.join("child.json"),
        r#"{"type":"object","properties":{"y":{"type":"string"}}}"#,
    )
    .expect("write child");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            temp_dir.path().to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let root_rs = std::fs::read_to_string(out_dir.path().join("root.rs")).expect("read root.rs");
    let child_rs = std::fs::read_to_string(out_dir.path().join("nested").join("child.rs"))
        .expect("read nested/child.rs");
    assert!(
        root_rs.contains("pub x: Option<String>"),
        "root.rs should have field x"
    );
    assert!(
        child_rs.contains("pub y: Option<String>"),
        "nested/child.rs should have field y"
    );
    let root_mod = std::fs::read_to_string(out_dir.path().join("mod.rs")).expect("read mod.rs");
    let nested_mod = std::fs::read_to_string(out_dir.path().join("nested").join("mod.rs"))
        .expect("read nested/mod.rs");
    assert!(
        root_mod.contains("pub mod nested;") && root_mod.contains("pub mod root;"),
        "root mod.rs should re-export nested and root: {root_mod}"
    );
    assert!(
        nested_mod.contains("pub mod child;"),
        "nested/mod.rs should re-export child: {nested_mod}"
    );
}

#[test]
fn cli_generate_rust_ingestion_single_failure_logs_path_and_exits_nonzero() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let bad_path = temp_dir.path().join("bad.json");
    std::fs::write(&bad_path, r#"{"type":"object","properties":{}"#).expect("write invalid json");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            bad_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(!output.status.success(), "should exit non-zero");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("bad.json"),
        "stderr should contain failing file path: {stderr}"
    );
    assert!(
        stderr.contains("invalid JSON Schema") || stderr.contains("EOF"),
        "stderr should contain error reason: {stderr}"
    );
}

#[test]
fn cli_generate_rust_ingestion_multiple_failures_logs_all_and_exits_nonzero() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let bad1 = temp_dir.path().join("bad1.json");
    let bad2 = temp_dir.path().join("bad2.json");
    std::fs::write(&bad1, r#"{"type":"object"#).expect("write bad1");
    std::fs::write(&bad2, r"not json").expect("write bad2");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            bad1.to_str().unwrap(),
            bad2.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(!output.status.success(), "should exit non-zero");
    let stderr = String::from_utf8_lossy(&output.stderr);
    let expected_bad1 = stderr.contains("bad1.json");
    let expected_bad2 = stderr.contains("bad2.json");
    assert!(
        expected_bad1 && expected_bad2,
        "stderr should contain both failing file paths; stderr: {stderr}"
    );
}

#[test]
fn cli_generate_rust_ingestion_partial_success_no_output_written() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let good_path = temp_dir.path().join("good.json");
    let bad_path = temp_dir.path().join("bad.json");
    std::fs::write(
        &good_path,
        r#"{"type":"object","properties":{"x":{"type":"string"}}}"#,
    )
    .expect("write good");
    std::fs::write(&bad_path, r#"{"type":"object"#).expect("write bad");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            good_path.to_str().unwrap(),
            bad_path.to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(!output.status.success(), "should exit non-zero");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("bad.json"),
        "stderr should log failing file: {stderr}"
    );
    let good_rs = out_dir.path().join("good.rs");
    assert!(
        !good_rs.exists(),
        "no output should be written when any ingestion fails: {good_rs:?} should not exist"
    );
}

#[test]
fn cli_generate_rust_hyphenated_paths_sanitized_and_mod_rs_emitted() {
    let temp_dir = tempfile::tempdir().expect("temp dir");
    let sub_dir = temp_dir.path().join("sub-dir");
    std::fs::create_dir_all(&sub_dir).expect("create sub-dir");
    std::fs::write(
        temp_dir.path().join("schema-1.json"),
        r#"{"type":"object","properties":{"a":{"type":"string"}}}"#,
    )
    .expect("write schema-1");
    std::fs::write(
        sub_dir.join("schema-2.json"),
        r#"{"type":"object","properties":{"b":{"type":"string"}}}"#,
    )
    .expect("write schema-2");
    let out_dir = tempfile::tempdir().expect("temp out dir");
    let output = Command::new(jsonschemars_bin())
        .args([
            "generate",
            "rust",
            "-o",
            out_dir.path().to_str().unwrap(),
            temp_dir.path().to_str().unwrap(),
        ])
        .output()
        .expect("run jsonschemars");
    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let schema_1_rs = out_dir.path().join("schema_1.rs");
    let sub_dir_schema_2 = out_dir.path().join("sub_dir").join("schema_2.rs");
    assert!(
        schema_1_rs.exists(),
        "schema_1.rs should exist (sanitized from schema-1.json)"
    );
    assert!(
        sub_dir_schema_2.exists(),
        "sub_dir/schema_2.rs should exist (sanitized path)"
    );
    let root_mod = std::fs::read_to_string(out_dir.path().join("mod.rs")).expect("read mod.rs");
    let expected_root =
        root_mod.contains("pub mod schema_1;") && root_mod.contains("pub mod sub_dir;");
    assert!(
        expected_root,
        "root mod.rs should declare schema_1 and sub_dir: {root_mod}"
    );
    let sub_dir_mod = std::fs::read_to_string(out_dir.path().join("sub_dir").join("mod.rs"))
        .expect("read sub_dir/mod.rs");
    assert!(
        sub_dir_mod.contains("pub mod schema_2;"),
        "sub_dir/mod.rs should declare schema_2: {sub_dir_mod}"
    );
}

#[test]
fn cli_validate_valid_payload_exit_zero() {
    let schema_json = r#"{"type":"object","properties":{"x":{"type":"string"}}}"#;
    let mut schema_file = tempfile::NamedTempFile::new().expect("temp schema");
    std::io::Write::write_all(&mut schema_file, schema_json.as_bytes()).expect("write schema");
    schema_file.flush().expect("flush schema");
    let payload_json = r#"{"x":"ok"}"#;
    let mut child = Command::new(jsonschemars_bin())
        .args(["validate", "-s", schema_file.path().to_str().unwrap()])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn jsonschemars");
    std::io::Write::write_all(child.stdin.as_mut().unwrap(), payload_json.as_bytes())
        .expect("write payload");
    let output = child.wait_with_output().expect("wait jsonschemars");
    assert!(
        output.status.success(),
        "validate should succeed: stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn cli_validate_invalid_payload_exit_nonzero_and_stderr() {
    let schema_json = r#"{"type":"object","required":["id"]}"#;
    let payload_json = r"{}";
    let mut schema_file = tempfile::NamedTempFile::new().expect("temp schema");
    std::io::Write::write_all(&mut schema_file, schema_json.as_bytes()).expect("write schema");
    schema_file.flush().expect("flush schema");
    let mut child = Command::new(jsonschemars_bin())
        .args(["validate", "-s", schema_file.path().to_str().unwrap()])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn jsonschemars");
    std::io::Write::write_all(child.stdin.as_mut().unwrap(), payload_json.as_bytes())
        .expect("write payload");
    let output = child.wait_with_output().expect("wait jsonschemars");
    assert!(!output.status.success(), "validate should fail");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert!(
        stderr.contains("missing required"),
        "stderr should mention missing required: {stderr}"
    );
}

#[test]
fn integration_parse_and_generate() {
    let json = r#"{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}"#;
    let schema_settings: JsonSchemaSettings = JsonSchemaSettings::builder().build();
    let schema: JsonSchema = parse_schema(json, &schema_settings).expect("parse schema");
    let code_gen_settings: CodeGenSettings = CodeGenSettings::builder().build();
    let bytes = generate_rust(&[schema], &code_gen_settings).expect("generate");
    let actual = String::from_utf8(bytes[0].clone()).expect("utf8");
    let expected = r"//! Generated by json-schema-rs. Do not edit manually.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Root {
    pub id: String,
}

";
    assert_eq!(expected, actual);
}
